name: Deploy to VMs

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy to Multiple VMs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        vm: 
          - host: ${{ secrets.SSH_HOST }}
            user: ${{ secrets.SSH_USER }}
            port: ${{ secrets.SSH_PORT }}
            key: ${{ secrets.SSH_KEY }}
          - host: ${{ secrets.SSH_HOST_VM2 }}
            user: ${{ secrets.SSH_USER_VM2 }}
            port: ${{ secrets.SSH_PORT_VM2 }}
            key: ${{ secrets.SSH_KEY_VM2 }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy app to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ matrix.vm.host }}
          username: ${{ matrix.vm.user }}
          port: ${{ matrix.vm.port }}
          key: ${{ matrix.vm.key }}
          source: "**"
          target: "~/springapp"

      - name: Check and Kill Process on Port 8080 (in VM)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.vm.host }}
          username: ${{ matrix.vm.user }}
          port: ${{ matrix.vm.port }}
          key: ${{ matrix.vm.key }}
          script: |
            process_id=$(lsof -t -i :8080)
            if [ -n "$process_id" ]; then
              echo "Processo encontrado na porta 8080 (PID: $process_id). Matando o processo."
              kill -9 $process_id
            else
              echo "Nenhum processo encontrado na porta 8080."
            fi

      - name: Build and Start SpringApp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.vm.host }}
          username: ${{ matrix.vm.user }}
          port: ${{ matrix.vm.port }}
          key: ${{ matrix.vm.key }}
          script: |
            cd ~/springapp
            mvn clean install -DskipTests=true
            cd target
            nohup java -jar pixel-0.0.1-SNAPSHOT.jar > ~/springapp/springapp.log 2>&1 &
