name: Deploy to Multiple VMs

on:
  push:
    branches:
      - main  

jobs:
  deploy-to-vm1:
    name: Deploy to VM1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy app to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "**"
          target: "~/springapp"
          
      - name: Check and Kill Process on Port 8080 (in VM)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            process_id=$(lsof -t -i :8080)
            if [ -n "$process_id" ]; then
              echo "Killing process on port 8080 (PID: $process_id)"
              kill -9 $process_id
            fi

      - name: Build and Start SpringApp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/springapp
            /opt/maven/bin/mvn clean install -DskipTests=true
            cd target
            nohup java -jar pixel-0.0.1-SNAPSHOT.jar > ~/springapp/springapp.log 2>&1 &

  deploy-to-vm2:
    name: Deploy to VM2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy app to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_VM2 }}
          username: ${{ secrets.SSH_USER_VM2 }}
          port: ${{ secrets.SSH_PORT_VM2 }}
          key: ${{ secrets.SSH_KEY_VM2 }}
          source: "**"
          target: "~/springapp"
          
      - name: Check and Kill Process on Port 8080 (in VM)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_VM2 }}
          username: ${{ secrets.SSH_USER_VM2 }}
          port: ${{ secrets.SSH_PORT_VM2 }}
          key: ${{ secrets.SSH_KEY_VM2 }}
          script: |
            process_id=$(lsof -t -i :8080)
            if [ -n "$process_id" ]; then
              echo "Killing process on port 8080 (PID: $process_id)"
              kill -9 $process_id
            fi

      - name: Build and Start SpringApp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_VM2 }}
          username: ${{ secrets.SSH_USER_VM2 }}
          port: ${{ secrets.SSH_PORT_VM2 }}
          key: ${{ secrets.SSH_KEY_VM2 }}
          script: |
            cd ~/springapp
            /opt/maven/bin/mvn clean install -DskipTests=true
            cd target
            nohup java -jar pixel-0.0.1-SNAPSHOT.jar > ~/springapp/springapp.log 2>&1 &
