name: Deploy to VM

on:
  push:
    branches:
      - main  

jobs:
 deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy app to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # Github path
          source: "**"
          # VPS path
          target: "~/springapp"
          
      - name: Check and Kill Process on Port 80 (in VM)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Verifica se há algum processo rodando na porta 80
            process_id=$(lsof -t -i :80)
            if [ -n "$process_id" ]; then
              echo "Processo encontrado na porta 80 (PID: $process_id). Matando o processo."
              kill -9 $process_id  # Mata o processo que está usando a porta 80
            else
              echo "Nenhum processo encontrado na porta 80."
            fi

      - name: Build and Start SpringApp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/springapp
            mvn clean install -DskipTests=true
            cd target
            nohup java -jar pixel-0.0.1-SNAPSHOT.jar > ~/springapp/springapp.log 2>&1 &
