name: Deploy to VM

on:
  push:
    branches:
      - main  

jobs:
 deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy app to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          # Github path
          source: "**"
          # VPS path
          target: "~/springapp"


      - name: Build and Start SpringApp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/springapp
            mvn clean install -DskipTests=true
            cd target
            nohup java -jar pixel-0.0.1-SNAPSHOT.jar &

